version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: clinic-db
    environment:
      POSTGRES_DB: clinicdb
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: clinic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinic.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
